language: objective-c
os: osx
matrix:
    include:
        - {os: osx, osx_image: xcode6.4}
        - {os: osx, osx_image: xcode7.3}
        - {os: osx, osx_image: xcode8.3}
        - {os: osx, osx_image: xcode9}
        - {os: osx, osx_image: xcode9.1}
        - {os: osx, osx_image: xcode9.2}
        - {os: osx, osx_image: xcode9.3}
        - {os: osx, osx_image: xcode9.4}
        - {os: osx, osx_image: xcode10}
before_install:
    - brew update
    - 'which cmake || ( brew install cmake )'
install:
    - make build/release
    - cd build/release; make install
script: which -a cmuscontrold
