name: CmusControl

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        zig-version:
          - '0.15.0'
          - '0.15.1'
          - '0.15.2'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Check Zig version
        run: zig version

      - name: Build
        run: zig build --release

      - name: Check help
        run: ./zig-out/bin/cmuscontrold --help
